name: PowerfulFireworks
version: '1.0-SNAPSHOT'
main: org.eu.pcraft.powerfulfireworks.PowerfulFireworks
description: PowerfulFireworks
api-version: '1.19'
dependencies:
  server:
    Vault:
      load: AFTER
      required: true
      join-classpath: true