name: PowerfulFireworks
version: '1.0-SNAPSHOT'
main: org.eu.pcraft.powerfulfireworks.PowerfulFireworks
description: PowerfulFireworks
api-version: '1.19'
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true
    NBTAPI:
      load: BEFORE
      required: false
      join-classpath: true