name: PowerfulFireworks
version: '1.6'
main: org.eu.pcraft.powerfulfireworks.PowerfulFireworks
description: PowerfulFireworks
api-version: '1.19'
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true